const student=[
    {
        roll:48,
        name:"romi",
        age:22,
        loc:"mirpur"
    },
    {
        roll:33,
        name:"jakiya",
        age:33,
        loc:"bonani"
    },
    {
        roll:41,
        name:"sufiya",
        age:13,
        loc:"mirpur"
    },
    {
        roll:12,
        name:"saira",
        age:17,
        loc:"rungpur"
    },
    {
        roll:24,
        name:"piya",
        age:22,
        loc:"mirpur"
    },
    {
        roll:17,
        name:"nadia",
        age:23,
        loc:"bonani"
    },
    {
        roll:56,
        name:"sajeda",
        age:30,
        loc:"mirpur"
    },
    {
        roll:29,
        name:"borsha",
        age:30,
        loc:"mirpur"
    },
    {
        roll:30,
        name:"korim",
        age:23,
        loc:"sherpur"
    },
    {
        roll:16,
        name:"raihan",
        age:20,
        loc:"bonani"
    },
    {
        roll:15,
        name:"jamir",
        age:23,
        loc:"mirpur"
    },
    {
        roll:18,
        name:"roni",
        age:10,
        loc:"bonani"
    },
    {
        roll:56,
        name:"sahin",
        age:30,
        loc:"rongpur"
    },
    {
        roll:44,
        name:"sahin",
        age:90,
        loc:"jamalpur"
    },
    {
        roll:399,
        name:"sahin",
        age:14,
        loc:"mirpur"
    },
    {
        roll:89,
        name:"sahin",
        age:30,
        loc:"jamalpur"
    },
    {
        roll:56,
        name:"roki",
        age:30,
        loc:"bonani"
    },
    {
        roll:111,
        name:"sobuz",
        age:30,
        loc:"mirpur"
    },
    {
        roll:19,
        name:"sahin",
        age:17,
        loc:"mirpur"
    },
    {
        roll:5,
        name:"sahin",
        age:30,
        loc:"bogora"
    },
    {
        roll:58,
        name:"saleha",
        age:30,
        loc:"bonani"
    },
    {
        roll:43,
        name:"sahin",
        age:40,
        loc:"mirpur"
    },
    {
        roll:89,
        name:"jakariya",
        age:70,
        loc:"jamalpur"
    },
    {
        roll:32,
        name:"aisha",
        age:30,
        loc:"mirpur"
    },
    {
        roll:16,
        name:"saniya",
        age:23,
        loc:"sherpur"
    },
    {
        roll:2,
        name:"poli",
        age:19,
        loc:"mirpur"
    },
    {
        roll:333,
        name:"tipu",
        age:24,
        loc:"jamalpur"
    },
    {
        roll:77,
        name:"rabiya",
        age:11,
        loc:"sherpur"
    },
    {
        roll:99,
        name:"rukiya",
        age:22,
        loc:"mirpur"
    },
    {
        roll:23,
        name:"saika",
        age:30,
        loc:"mirpur"
    },
    {
        roll:22,
        name:"tisha",
        age:20,
        loc:"mirpur"
    },
    {
        roll:100,
        name:"raihan",
        age:30,
        loc:"bonani"
    },
    {
        roll:90,
        name:"rakib",
        age:30,
        loc:"mirpur"
    },
    {
        roll:22,
        name:"soniya",
        age:30,
        loc:"borishal"
    },
    {
        roll:66,
        name:"sahina",
        age:30,
        loc:"sherpur"
    },
    {
        roll:55,
        name:"sahin",
        age:30,
        loc:"mirpur"
    },
    {
        roll:33,
        name:"sabina",
        age:10,
        loc:"mirpur"
    },
    {
        roll:1,
        name:"monir",
        age:20,
        loc:"mirpur"
    },
    {
        roll:40,
        name:"rahim",
        age:30,
        loc:"mirpur"
    },
    {
        roll:39,
        name:"sahin",
        age:40,
        loc:"rongpur"
    },
    {
        roll:11,
        name:"ismail",
        age:30,
        loc:"bonani"
    },
    {
        roll:42,
        name:"sojib",
        age:30,
        loc:"mirpur"
    },
    {
        roll:43,
        name:"rakib",
        age:30,
        loc:"sherpur"
    },
    {
        roll:49,
        name:"sohan",
        age:35,
        loc:"rongpur"
    },
    {
        roll:45,
        name:"sofik",
        age:30,
        loc:"bonani"
    },
    {
        roll:44,
        name:"sabiha",
        age:30,
        loc:"mirpur"
    },
    {
        roll:22,
        name:"sahin",
        age:20,
        loc:"mirpur"
    },
    {
        roll:3,
        name:"robin",
        age:35,
        loc:"bonani"
    },
    {
        roll:21,
        name:"sahina",
        age:40,
        loc:"rogpur"
    },
    {
        roll:50,
        name:"sahin",
        age:30,
        loc:"mirpur"
    }

];
/** */
student.map(( data)=>{
   if(data.loc=="mirpur" || data.loc=="bonani" ){
      console.log(`
      roll: ${data.roll}
      name: ${data.name}
      age: ${data.age}
      location: ${(data.loc).sort()}
      `)
   }
  
    
});